name: juangpuw
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Pythonversion
  - python=3.9

  # PyTorch + CUDA 11.8 (officiell rekommendation)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # Analys/ML-paket
  - numpy
  - pandas=1.2.4
  - matplotlib
  - scikit-learn
  - tqdm
  - seaborn

  # Verktyg
  - ipython=7.25.0
  - pyyaml=5.4.1
  - jupyterlab
  - ipywidgets

  # d2l
  - d2l=0.17.6

  # pip för ev. framtida tillägg
  - pip
