name: juancpuw
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Pythonversion (kompatibel med dina ursprungliga krav och d2l/pandas 1.2.4)
  - python=3.9

  # PyTorch CPU
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly

  # Analys/ML-paket
  - numpy
  - pandas=1.2.4
  - matplotlib
  - scikit-learn
  - tqdm
  - seaborn

  # Verktyg med dina önskade versioner
  - ipython=7.25.0
  - pyyaml=5.4.1
  - jupyterlab
  - ipywidgets

  # d2l (Dive into Deep Learning)
  - d2l=0.17.6

  # pip finns om du vill lägga till extra saker senare
  - pip
