source(file = 'manuscript/manuscriptcommon.R')
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(forcats)
library(readxl)
source(file = 'manuscript/metric_helpers_common.R')
source(file = 'manuscript/generic_plot_helpers.R')
